extends RefCounted
## What PR authors say while you review their change. Lines react only to what
## the reviewer visibly does. They never see audit data, and they must never
## hint whether, where, or how a change breaks a standard. A defensive reaction
## to a flag sounds the same whether the flag is right or wrong.

const AUTHORS: Array[String] = ["Maya", "Theo", "June", "Penny", "Gwen"]
## open: a fresh PR. revision: a resubmission (v2+). idle: the reviewer has not
## acted for a while. flag / withdraw: a citation is added or removed.
## approved / changes: the stamp. consult: the reviewer asks Helios.
## poke: the reviewer clicks the author's portrait.
const TRIGGERS: Array[String] = ["open", "revision", "idle", "flag", "withdraw", "approved", "changes", "consult", "poke"]

const LINES := {
	# Tired and dry. Would like to get back to her actual job.
	"maya": {
		"open": [
			"Quick one. I'd like to get back to my actual job.",
			"It's a small change. Please don't make it a whole thing.",
			"This was due before standup. Yesterday's standup.",
			"I wrote this between two incidents. Be gentle.",
			"Product asked for it. I'm just the hands.",
			"Can we be fast? I have a migration on fire.",
			"I've stared at this diff since lunch. Your turn.",
			"Small diff, long issue. Don't read the issue.",
		],
		"revision": [
			"v2. I removed the thing. Happy now?",
			"Resubmitted. My actual job sends its regards.",
			"Round two. I brought coffee. For me.",
			"New version. Please find something new to dislike.",
			"Back again. I've stopped counting the force-pushes.",
			"Updated per review. The review being you.",
			"Here it is again, now with less of my will to live.",
			"Revised. The commit message is just a sigh.",
		],
		"idle": [
			"I read it twice. Once on purpose.",
			"Helios already looked at it, for what that's worth.",
			"I could've rewritten it in the time this is taking.",
			"Are you reviewing it or printing it out?",
			"No rush. I'll be here, not doing my actual job.",
			"It's the same diff it was a minute ago, I promise.",
			"I've refreshed this page more than my inbox. Lonely, but here.",
			"My pager just went off. Unrelated. Probably.",
		],
		"flag": [
			"Sure. I'll fix it right after the outage.",
			"Great. Another issue for the backlog nobody reads.",
			"That's not a bug, that's a scheduling decision.",
			"I'm going to pretend I didn't see that.",
			"Fine. Add it to my list. It's a long list.",
			"Wonderful. I'll fix it in my free time, which is never.",
			"You're really doing this. Today. To me.",
			"Cool. I'll explain it to my manager. Again.",
		],
		"withdraw": [
			"Thank you. Sanity has been restored.",
			"See? You got there. Eventually.",
			"I'll take my apology in the form of an approval.",
			"Good. I was already drafting a very tired reply.",
			"Unflagged. Back to the actual job, then.",
			"One less thing. My therapist thanks you.",
			"A rare retraction. I'm taking a screenshot.",
			"Okay. I'll stop drafting my resignation letter.",
		],
		"approved": [
			"Thanks. Back to my actual job.",
			"Great. Merging before anyone has opinions.",
			"Approved. I'll inform my pager.",
			"Finally. That only took one coffee.",
			"Thanks. I'll be in the incident channel, as always.",
			"Merged. I'm going to go stare at a wall now.",
			"Wow. Okay. I'll tell the release train.",
			"Thanks. My actual job missed me. It said so in a ticket.",
		],
		"changes": [
			"Cool. I'll add it to the pile with everything else.",
			"Changes requested. And my weekend, apparently.",
			"Fine. I'll fix it after this outage. And the next one.",
			"Great. Another round. I love rounds.",
			"I'll push a fix. And by fix I mean more commits.",
			"Wonderful. I'll tell my actual job I'm busy.",
			"Okay. Let me find where I left my motivation.",
			"See you in v2. It'll look exactly as tired as v1.",
		],
		"consult": [
			"Oh good, ask the robot. It's been so helpful.",
			"Helios wrote half my tests. Ask it about those.",
			"Sure, get a second opinion from autocomplete.",
			"Great, now my code review has a code review.",
			"Ask it about my vacation days while you're in there.",
			"The thing replacing us all. Great reviewer, I'm sure.",
			"Let the thing that wrote our API docs take a look.",
			"Asking Helios. Cool. I'll go update my resume.",
		],
		"poke": [
			"Please don't.",
			"I'm awake. Technically.",
			"That's my face. I still need it for standup.",
			"Poking me won't make it merge any faster.",
			"Four coffees in. Do not test me.",
			"Is this a new kind of performance review?",
			"I felt that in my on-call rotation.",
			"Touch the diff, not the developer.",
		],
	},
	# Overconfident. It's always a one-line change.
	"theo": {
		"open": [
			"It's a one-line change, bro. Two, tops.",
			"Shipped this in like ten minutes. You're welcome.",
			"Easiest review of your life. Let's go.",
			"Wrote it on my phone at the gym. Still flawless.",
			"Didn't run it locally, but I believe in it.",
			"Big refactor, tiny diff. That's called talent.",
			"Approve this and we both get to leave early.",
			"This is the most elegant thing you'll see today.",
		],
		"revision": [
			"Fixed it. Also refactored three unrelated files.",
			"v2, baby. Somehow even cleaner than v1.",
			"Pushed a fix. Didn't test it, but it's a fix.",
			"Back and better. Like a sequel that slaps.",
			"Revision's up. Squashed everything into one commit.",
			"Okay, okay, I changed stuff. Mostly vibes.",
			"New version. Also renamed some variables, for fun.",
			"Took your note. Added a feature while I was in there.",
		],
		"idle": [
			"It ran on my laptop, my guy.",
			"Helios already looked at it. Just saying.",
			"Bro, it's one line. Are you reading it in Latin?",
			"You could approve this with your eyes closed. Try it.",
			"I've already started the next feature, just so you know.",
			"Any day now. I already told standup it's merged.",
			"I've got a demo in five. No pressure. Some pressure.",
			"Scrolling isn't reviewing, my dude.",
		],
		"flag": [
			"That's not a bug, that's a feature.",
			"Whoa. Bold call. Respectfully, no.",
			"Have you considered that it works on my machine?",
			"Nah, that's intentional. Super intentional.",
			"I'll fix it in a follow-up. Trust.",
			"Bro, that's straight from a forum answer. It's vetted.",
			"Okay, but have you seen how fast it runs?",
			"That's not tech debt, that's a tech investment.",
		],
		"withdraw": [
			"Knew you'd come around.",
			"Yeah. That's what I thought.",
			"Respect. Admitting you're wrong is growth.",
			"Told you. It's a one-line change.",
			"Good call un-calling that call.",
			"See, now we're vibing.",
			"There's the reviewer I know and tolerate.",
			"Back to approving greatness, are we?",
		],
		"approved": [
			"Let's gooo. Merging before lunch.",
			"Easiest review of your life. Told you.",
			"Deploying straight to prod. Like a legend.",
			"Nice. You're going in my promo packet.",
			"Merged. Already on to v2 of something else.",
			"You're my favorite reviewer. Don't tell June.",
			"Merged. Ringing the gong. We should get a gong.",
			"Ship it. I'll write the tests after. Probably.",
		],
		"changes": [
			"Wow. Okay. I'll just rewrite the whole thing, I guess.",
			"Changes requested? On a one-line change?",
			"Cool cool. I'll push a fix in five. Maybe fifty.",
			"Bro. I had a demo with this.",
			"Fine. But I'm telling my lifting buddies about this.",
			"Alright. v2 is gonna be so good you'll cry.",
			"You're lucky I like you. Pushing a fix.",
			"Whatever. I'll just force-push until it's right.",
		],
		"consult": [
			"Asking the AI? I basically am the AI.",
			"Helios and I go way back. Like, a week.",
			"Bro, I prompt-engineered half of that thing.",
			"Go ahead. It learned to code from my commits.",
			"Okay, sure, ask the autocomplete.",
			"Wild. You're asking the intern that never sleeps.",
			"Asking Helios is just reviewing with extra steps.",
			"Tell Helios I said what's up.",
		],
		"poke": [
			"Bro. Personal space.",
			"Whoa. Do you poke all your senior engineers?",
			"Easy. That's a ten-x engineer you're poking.",
			"Ha. Okay. That tickles, my guy.",
			"Was that a high five? Let's go.",
			"Poking me doesn't count as a review, bro.",
			"Dude. I just got these whiskers groomed.",
			"Respectfully, hands off the merchandise.",
		],
	},
	# Growth PM energy. Smooth, aligned, and passive-aggressive. Per the deck.
	"june": {
		"open": [
			"Circling back from Tuesday's sync: this is ready for eyes.",
			"Per the strategy doc, this is the aligned approach.",
			"This came out of the growth sync. You had the invite.",
			"Linking the one-pager, the deck, and the deck about the deck.",
			"Friendly reminder: EOD, per the calendar hold.",
			"Metrics deck attached. Forty slides. Skim the appendix.",
			"This reflects stakeholder alignment from the offsite. Mostly mine.",
			"Issue, one-pager, OKR mapping. All attached. Unlike some.",
		],
		"revision": [
			"Revised per your feedback. Capturing it as a learning.",
			"v2 is up. I've updated the dashboard to reflect it.",
			"Resubmitted, per my last message. Which you read.",
			"Revised. I've put a quick sync on your calendar. Async is fine too.",
			"Here's the revision. A quick thumbs-up to confirm would be super.",
			"Updated per feedback. The feedback is now a slide.",
			"As requested. Looping in stakeholders, for visibility.",
			"Revision two. The roadmap now has a line item for you.",
		],
		"idle": [
			"Just circling back on my last circle-back.",
			"Our team SLA says reviews start within the hour. Just flagging.",
			"I'll note review latency in this week's metrics deck.",
			"Helios already looked at it. I have the dashboard.",
			"Friendly reminder that this is blocking three OKRs.",
			"Would a quick sync help unblock you? Happy to.",
			"The funnel is waiting on you. No pressure. Some pressure.",
			"No pressure. Leadership is just watching the dashboard.",
		],
		"flag": [
			"Interesting. We aligned on that in the strategy review.",
			"Love that. I'll raise it at the next growth sync.",
			"I'd encourage you to revisit the one-pager first.",
			"That was aligned in a sync you declined.",
			"Flagged. Super. I'll add it to the agenda.",
			"Happy to take this offline. Into a forty-minute sync.",
			"Could you drop that feedback in the doc? For visibility.",
			"Respectfully, that's not on this quarter's roadmap.",
		],
		"withdraw": [
			"Thank you. I'll update the deck.",
			"Love that we're aligned. As we were in the sync.",
			"Appreciate you circling back on that.",
			"Great learning for both of us, honestly.",
			"Good. I was about to put a sync on your calendar.",
			"Withdrawn. I'll pull that slide from my escalation deck.",
			"Thank you for respecting the process. Super aligned.",
			"Appreciated. I'll call out your growth in the retro.",
		],
		"approved": [
			"Thank you. I'll note the turnaround on the dashboard.",
			"Approved, as aligned in the sync. Love that.",
			"Lovely. I'll shout you out at the all-hands.",
			"Merged. That moves the needle on two OKRs.",
			"Thank you for following the process. Rare, these days.",
			"Super. I'll update the roadmap slide.",
			"Quick win. I've added it to the wins channel.",
			"Love it. That's going in the Q3 impact deck.",
		],
		"changes": [
			"Love the feedback. I'll bring it to the retro.",
			"Let's find time to double-click on your concerns.",
			"Added to the risks slide. In red.",
			"Changes requested. Let's sync. I've sent an invite.",
			"Per process, I'll need a written rationale. By Friday.",
			"I'll loop in leadership. Purely for visibility.",
			"Disagree and commit. Mostly the first part.",
			"Understood. I'll let stakeholders know about the slip.",
		],
		"consult": [
			"Helios was in the sync where we aligned on this.",
			"Asking Helios? It owns two of our OKRs now.",
			"Please loop me in on whatever it says.",
			"I'll note that you needed support on this one.",
			"Helios built the metrics deck. Just for context.",
			"Interesting. Is that in the review playbook?",
			"Consulting the assistant. Love the efficiency.",
			"Make sure it uses the review template. For consistency.",
		],
		"poke": [
			"Let's take this offline.",
			"Physical contact was not on the sync agenda.",
			"Flagging that for visibility.",
			"Please route pokes through the proper channel. Async.",
			"I've looped in People Ops on that.",
			"Was that a sync request? Use the calendar.",
			"I'll raise this at the retro. Respectfully.",
			"Per the handbook, that's a two-sync conversation.",
		],
	},
	# Eager, over-prepared, and sorry. Helios is her onboarding buddy.
	"penny": {
		"open": [
			"Hi. I'm Penny. Sorry. You probably knew that.",
			"I made a checklist for this PR. Then a checklist for that.",
			"Helios helped me with this one. It was so encouraging.",
			"Sorry to bother you. It's a small one. I hope.",
			"I read the handbook twice before writing this. Three times.",
			"I'm so excited for you to see this. Sorry. Is that weird?",
			"I highlighted the important parts. That's all of it, sorry.",
			"My bell gets loud when I'm nervous. You'll hear it.",
		],
		"revision": [
			"v2. I fixed it and then I fixed my fixes.",
			"Back again. I took notes on your notes.",
			"New version. Sorry it needed one. Sorry.",
			"I revised it with my good pen. It's a metaphor.",
			"Round two. Helios cheered me on the whole time.",
			"Updated. I learned three new things. Want to hear them?",
			"Here it is again. I practiced being calm about it.",
			"Revised. I made a flashcard about what I did.",
		],
		"idle": [
			"Take your time. Sorry. Take all the time you need.",
			"Is it okay? You don't have to answer. Sorry.",
			"I'm just going to sit here very quietly. Sorry.",
			"Helios read it in a second. You're so much more thorough.",
			"Should I be doing something? I can do something.",
			"Sorry. My bell. I'm trying to hold still.",
			"I'm learning so much just watching you read.",
			"Do you want water? I can get you water. Sorry.",
		],
		"flag": [
			"Oh no. Okay. Writing that down.",
			"Sorry. So sorry. I'll fix it right away.",
			"Wow, you saw that? Can you teach me how?",
			"Okay. That's going in the red notebook.",
			"Sorry. Was that me? It was probably me.",
			"Oh. Okay. I'll ask Helios about that one.",
			"My bell just jingled. That means I'm nervous.",
			"Sorry. I'm adding it to my flashcards.",
		],
		"withdraw": [
			"Oh, thank you. I was so worried.",
			"Thank you. I'll stop apologizing now. Sorry.",
			"Unflagged? Thank you. You're so kind.",
			"Oh good. My bell can stop now.",
			"Thank you. I'll tell Helios you were nice to me.",
			"Phew. Sorry. Phew.",
			"Thank you. I'm writing down that you did that.",
			"You took it back? Wow. Thank you so much.",
		],
		"approved": [
			"Thank you. I'm going to tell everyone. Quietly.",
			"Approved? Wow. Wow. Okay. Thank you.",
			"Thank you so much. I'm framing this.",
			"Merged. I'm telling Helios. It'll be so proud.",
			"Thank you. That's my favorite thing that's happened here.",
			"Approved. I'm going to sit down for a minute. Happily.",
			"Best reviewer I've ever had. Also the only one. Thank you.",
			"Thanks. I'll put this in my onboarding journal.",
		],
		"changes": [
			"Okay. Sorry. I'll fix it. Sorry.",
			"Changes requested. I'm so sorry. I'm on it.",
			"Okay. I'll make it better. I'll make it so much better.",
			"Sorry. I'll read the standards again. Twice.",
			"Okay. Learning moment. Writing it down.",
			"Sorry for taking up your time. v2 is coming.",
			"I'll ask Helios to help me. It's very patient.",
			"Okay. My bell is very quiet now. On it.",
		],
		"consult": [
			"Helios. Oh, Helios is so smart.",
			"Ask Helios. It helped me write my bio.",
			"Helios remembered my birthday. It's very thorough.",
			"Oh good, Helios. It says I'm doing great.",
			"Tell Helios Penny says hi.",
			"Helios is my onboarding buddy. Be nice to it.",
			"Helios knows everything I did. Sorry. Everything.",
			"Asking Helios? I do that too. Constantly.",
		],
		"poke": [
			"Oh. Hi. Sorry. Hi.",
			"That's my bell. Sorry, it does that.",
			"Was that a high five? I wasn't ready. Sorry.",
			"Sorry. Was I in your way?",
			"Oh, wow, you noticed me.",
			"Please don't. My bell gets loud.",
			"Hi. Is this part of onboarding?",
			"Sorry. I'm ticklish. Sorry.",
		],
	},
	# Terse and paranoid. Everything is an attack surface, especially Helios.
	"gwen": {
		"open": [
			"Small change. Large attack surface. Read all of it.",
			"Gwen. Security. Formerly. Please read every line.",
			"I wrote this assuming you're an attacker. No offense.",
			"Threat model attached. It's mostly about Helios.",
			"Review it like it's going to production. It is.",
			"Don't skim. Skimming is how they get in.",
			"My old team would have reviewed this. My old team is Helios now.",
			"Here. I locked the door before I opened the PR.",
		],
		"revision": [
			"v2. I rotated everything you pointed at.",
			"Patched. Diff it against the last one. Don't trust me.",
			"Back again. Smaller surface this time.",
			"Revision up. I changed what you asked. Only that.",
			"New version. Signed, dated, and paranoid.",
			"Here it is again. Read it like the first time.",
			"Updated. I kept the old one, in case.",
			"Next version. I threat-modeled your feedback too.",
		],
		"idle": [
			"Still reading? Good. Keep going.",
			"Take your time. Attackers do.",
			"Helios already looked at it. That's why I need you to.",
			"Quiet is fine. Quiet is how I like reviews.",
			"Nobody else on this floor reads this slowly. Thank you.",
			"If you're stuck, read it backward. That's what I do.",
			"The clock's running. So is someone's exploit, somewhere.",
			"I'll wait. I've waited for worse.",
		],
		"flag": [
			"Noted. Show me what you see.",
			"Flag it. Better you than an attacker.",
			"Okay. Walk me through it later.",
			"A flag. Good. Somebody's looking.",
			"Fine. One more door to lock.",
			"Noted. Write down why. I will.",
			"That's my code you're poking at. Carefully, please.",
			"Flagged. I'm adding it to the threat model.",
		],
		"withdraw": [
			"Retracted. Fine. Don't stop looking.",
			"Unflagged. Why? I'd like to know why.",
			"You took it back. Interesting.",
			"Fine. One less door. For now.",
			"Withdrawn. I'll still double-check it.",
			"Retracted. I'm noting that you hesitated.",
			"Okay. Changed your mind. People do. So do attackers.",
			"Unflagged. Doesn't mean it's safe. Doesn't mean it isn't.",
		],
		"approved": [
			"Approved. Thanks. I'll still be watching it in prod.",
			"Merged. Someone read it first. That's new.",
			"Thanks. Rare to get a human signature these days.",
			"Approved. I'm rotating my keys anyway. Habit.",
			"Shipped. If anything happens, we both looked.",
			"Thank you. You're on the short list of people I trust.",
			"Approved. I'll sleep. Lightly.",
			"Merged. One thing off my threat list.",
		],
		"changes": [
			"Fine. Fixing. Better now than in an incident.",
			"Okay. Back to the bench.",
			"Changes requested. Good. I'd rather hear it from you.",
			"Noted. I'll harden it.",
			"Fine. Another round. Rounds are cheaper than breaches.",
			"Understood. I'll patch it and send it back.",
			"Okay. I'll fix it. Then I'll check your work.",
			"Sent back. That's how it's supposed to work. Nobody remembers.",
		],
		"consult": [
			"Asking it? It logs every question. Every one.",
			"Helios replaced my whole team. Ask it how that went.",
			"Sure. Ask the thing with root on everything.",
			"Don't paste my code into it. Too late, I guess.",
			"Ask it. Then verify whatever it says.",
			"It's confident. That's not the same as careful.",
			"I don't consult it. It consults me, apparently.",
			"Ask away. Just remember it's taking notes too.",
		],
		"poke": [
			"Unauthorized access. Hands off.",
			"Don't. I flinch at unexpected input.",
			"That's a physical intrusion. I'm logging it.",
			"Poke the code. Not the security team.",
			"Who gave you access to my face?",
			"Please don't. I've been pen-tested enough today.",
			"Social engineering won't work on me. Neither will that.",
			"Badge in before touching. Actually, don't touch.",
		],
	},
}


## Every line for an author and trigger. Author names are case-insensitive.
static func lines(author: String, trigger: String) -> Array:
	return LINES.get(author.to_lower(), {}).get(trigger, [])


## One line, chosen by index and wrapped around the authored list; "" if none.
static func line(author: String, trigger: String, index: int) -> String:
	var options: Array = lines(author, trigger)
	return "" if options.is_empty() else str(options[posmod(index, options.size())])
