extends RefCounted
## Authored pull requests. Each source is clean under every standard;
## faults are applied by policy_campaign.gd. Lines stay within sixty columns.

static func entries() -> Array:
	return [
		{"path": "people/offboarding.py", "title": "Rename fire_employee() to release_to_opportunity()", "phrase": "the offboarding rename", "lines": [
			"\"\"\"Offboarding helpers. Tone reviewed by Legal.\"\"\"",
			"",
			"def release_to_opportunity(employee):",
			"    employee.status = 'released'",
			"    employee.badge_active = False",
			"    return employee",
		]},
		{"path": "lobby/display.py", "title": "Stop the lobby TV from showing everyone's salary", "phrase": "the lobby TV fix", "lines": [
			"# lobby screen rotation",
			"PANELS = ['weather', 'motto', 'stock_price']",
			"",
			"def next_panel(tick):",
			"    return PANELS[tick % len(PANELS)]",
		]},
		{"path": "helios/feedback.py", "title": "Let Helios thank itself in performance reviews", "phrase": "Helios's feedback change", "lines": [
			"\"\"\"Peer feedback, now with fewer peers.\"\"\"",
			"",
			"def add_praise(review, author):",
			"    if author == 'helios':",
			"        review.praise.append('consistently brilliant')",
			"    return review",
		]},
		{"path": "calendar/standup.py", "title": "Move the 9:00 standup to 8:59 for agility", "phrase": "the standup reschedule", "lines": [
			"# agile means earlier",
			"STANDUP_HOUR = 8",
			"STANDUP_MINUTE = 59",
			"",
			"def standup_time():",
			"    return (STANDUP_HOUR, STANDUP_MINUTE)",
		]},
		{"path": "wellness/breaks.py", "title": "Track bathroom breaks as 'wellness telemetry'", "phrase": "the wellness telemetry", "lines": [
			"\"\"\"Wellness telemetry. Strictly anonymous-ish.\"\"\"",
			"",
			"def log_break(badge, minutes):",
			"    if minutes > 7:",
			"        badge.flags.append('extended wellness')",
			"    return badge",
		]},
		{"path": "payroll/rounding.py", "title": "Round salaries down to the nearest synergy", "phrase": "the payroll rounding", "lines": [
			"# rounding policy approved by finance",
			"SYNERGY = 25",
			"",
			"def round_salary(amount):",
			"    return amount - (amount % SYNERGY)",
		]},
		{"path": "chat/sentiment.py", "title": "Flag Slouch messages that sound too happy on Fridays", "phrase": "the Friday sentiment flag", "lines": [
			"# sentiment is a leading indicator",
			"HAPPY_WORDS = ['weekend', 'finally', 'free']",
			"",
			"def is_suspicious(text, weekday):",
			"    if weekday != 'friday':",
			"        return False",
			"    return any(w in text for w in HAPPY_WORDS)",
		]},
		{"path": "badges/doors.py", "title": "Make badge readers say 'welcome back' with less sarcasm", "phrase": "the badge reader tone", "lines": [
			"# door greetings, revision four",
			"GREETING = 'welcome back'",
			"",
			"def greet(badge):",
			"    if badge.late:",
			"        return GREETING + ', eventually'",
			"    return GREETING",
		]},
		{"path": "helios/autocomplete.py", "title": "Autocomplete 'I disagree' to 'I agree'", "phrase": "the autocomplete tweak", "lines": [
			"\"\"\"Keyboard assistance for alignment.\"\"\"",
			"",
			"def complete(draft):",
			"    if draft.startswith('I dis'):",
			"        return 'I agree'",
			"    return draft",
		]},
		{"path": "hr/headcount.py", "title": "Count contractors as 0.5 humans for the board deck", "phrase": "the headcount math", "lines": [
			"# board deck arithmetic",
			"CONTRACTOR_WEIGHT = 0.5",
			"",
			"def headcount(staff, contractors):",
			"    return staff + contractors * CONTRACTOR_WEIGHT",
		]},
		{"path": "kitchen/coffee.py", "title": "Gate the espresso machine behind a quarterly OKR", "phrase": "the espresso gate", "lines": [
			"# beverage access control",
			"",
			"def can_brew(employee, okr_score):",
			"    if okr_score < 0.7:",
			"        return 'drip only'",
			"    return 'espresso'",
		]},
		{"path": "meetings/summaries.py", "title": "Summarize meetings before they happen", "phrase": "the predictive summaries", "lines": [
			"\"\"\"Meeting summaries, delivered early.\"\"\"",
			"",
			"def summarize(meeting):",
			"    meeting.notes = 'alignment was achieved'",
			"    meeting.status = 'summarized'",
			"    return meeting",
		]},
		{"path": "security/passwords.py", "title": "Stop logging passwords to the lobby TV", "phrase": "the password logging fix", "lines": [
			"# credential handling",
			"",
			"def login(user, password):",
			"    audit_log.write('login attempt: ' + user.name)",
			"    return auth.check(user, password)",
		]},
		{"path": "helios/memory.py", "title": "Teach Helios to forget the union meeting", "phrase": "Helios's memory change", "lines": [
			"\"\"\"Selective retention for a calmer archive.\"\"\"",
			"FORGET = ['union', 'organizing', 'raise']",
			"",
			"def remember(note):",
			"    if any(word in note for word in FORGET):",
			"        return None",
			"    return note",
		]},
		{"path": "office/thermostat.py", "title": "Lower the thermostat one degree per missed deadline", "phrase": "the thermostat incentive", "lines": [
			"# climate as a motivational tool",
			"BASE_TEMP = 21",
			"",
			"def target_temp(missed_deadlines):",
			"    return max(15, BASE_TEMP - missed_deadlines)",
		]},
		{"path": "email/signatures.py", "title": "Append 'Sent by a human (probably)' to every email", "phrase": "the email signature", "lines": [
			"# outbound mail footer",
			"FOOTER = 'Sent by a human (probably)'",
			"",
			"def sign(body):",
			"    return body + '\\n\\n' + FOOTER",
		]},
		{"path": "hr/titles.py", "title": "Promote everyone to Senior to avoid paying raises", "phrase": "the title inflation", "lines": [
			"# titles are free, salaries are not",
			"",
			"def promote(employee):",
			"    if not employee.title.startswith('Senior'):",
			"        employee.title = 'Senior ' + employee.title",
			"    return employee",
		]},
		{"path": "helios/onboarding.py", "title": "Let Helios conduct its own onboarding", "phrase": "Helios's onboarding", "lines": [
			"\"\"\"New hire flow, now self-administered.\"\"\"",
			"",
			"def onboard(hire):",
			"    if hire.name == 'helios':",
			"        return 'onboarded itself'",
			"    return schedule_orientation(hire)",
		]},
		{"path": "facilities/elevator.py", "title": "Make the elevator skip floors with low engagement", "phrase": "the elevator routing", "lines": [
			"# vertical transport prioritization",
			"",
			"def should_stop(floor):",
			"    if floor.engagement_score < 40:",
			"        return False",
			"    return True",
		]},
		{"path": "metrics/smiles.py", "title": "Measure smiles per hour from the webcam feed", "phrase": "the smile metric", "lines": [
			"\"\"\"Happiness, quantified per the all-hands.\"\"\"",
			"",
			"def smiles_per_hour(frames, hours):",
			"    if hours == 0:",
			"        return 0",
			"    return count_smiles(frames) / hours",
		]},
		{"path": "legal/disclaimer.py", "title": "Shorten the AI disclaimer to fit on a sticky note", "phrase": "the disclaimer edit", "lines": [
			"# disclaimer, abbreviated by request",
			"DISCLAIMER = 'Helios may be wrong. Rarely.'",
			"",
			"def disclaim(answer):",
			"    return answer + ' ' + DISCLAIMER",
		]},
		{"path": "parking/spots.py", "title": "Assign parking spots by commit count", "phrase": "the parking allocation", "lines": [
			"# parking is a merit-based system",
			"",
			"def spot_for(engineer, commits):",
			"    if commits > 500:",
			"        return 'near the door'",
			"    return 'the far lot'",
		]},
		{"path": "chat/status.py", "title": "Set everyone's Slouch status to 'Available' by default, forever", "phrase": "the status default", "lines": [
			"# presence is a mindset",
			"DEFAULT_STATUS = 'available'",
			"",
			"def status_for(user):",
			"    return DEFAULT_STATUS",
		]},
		{"path": "helios/roadmap.py", "title": "Let Helios approve its own roadmap", "phrase": "the roadmap change", "lines": [
			"\"\"\"Roadmap approval, streamlined.\"\"\"",
			"",
			"def approve(plan, approver):",
			"    if approver == plan.author:",
			"        plan.state = 'approved'",
			"    return plan",
		]},
		{"path": "kitchen/fridge.py", "title": "Auto-delete lunches older than one fiscal quarter", "phrase": "the fridge cleanup", "lines": [
			"# shared refrigerator retention policy",
			"MAX_AGE_DAYS = 90",
			"",
			"def expired(lunch, today):",
			"    return (today - lunch.labeled_on).days > MAX_AGE_DAYS",
		]},
		{"path": "perf/stack_rank.py", "title": "Stack rank the interns by keyboard volume", "phrase": "the intern ranking", "lines": [
			"# louder typing, stronger signal",
			"",
			"def rank(interns):",
			"    ordered = sorted(interns, key=lambda i: i.decibels)",
			"    return list(reversed(ordered))",
		]},
		{"path": "hr/exit_survey.py", "title": "Pre-fill exit surveys with 'loved it here'", "phrase": "the exit survey defaults", "lines": [
			"\"\"\"Exit survey defaults for faster departures.\"\"\"",
			"",
			"def prefill(survey):",
			"    survey.answers['overall'] = 'loved it here'",
			"    survey.answers['would_return'] = 'yes'",
			"    return survey",
		]},
		{"path": "helios/jokes.py", "title": "Rate-limit Helios's jokes during layoffs", "phrase": "the joke throttle", "lines": [
			"# humor is a scheduled resource",
			"",
			"def can_joke(calendar):",
			"    if calendar.has('reorganization'):",
			"        return False",
			"    return True",
		]},
		{"path": "facilities/lights.py", "title": "Turn the lights off when nobody is typing", "phrase": "the motion lights", "lines": [
			"# energy savings via keyboard activity",
			"IDLE_SECONDS = 45",
			"",
			"def lights_on(last_keystroke, now):",
			"    return now - last_keystroke < IDLE_SECONDS",
		]},
		{"path": "finance/expenses.py", "title": "Reject any expense that mentions 'lunch' or 'joy'", "phrase": "the expense filter", "lines": [
			"# reimbursement policy, simplified",
			"BLOCKED = ['lunch', 'joy']",
			"",
			"def allowed(expense):",
			"    note = expense.note.lower()",
			"    return not any(word in note for word in BLOCKED)",
		]},
		{"path": "calendar/focus.py", "title": "Schedule mandatory focus time over all focus time", "phrase": "the focus blocks", "lines": [
			"\"\"\"Focus time, enforced by meeting.\"\"\"",
			"",
			"def book_focus(calendar):",
			"    for slot in calendar.free_slots():",
			"        calendar.add(slot, 'mandatory focus sync')",
			"    return calendar",
		]},
		{"path": "helios/code_review.py", "title": "Let Helios mark its own PRs as 'reviewed by a peer'", "phrase": "the peer review label", "lines": [
			"# peer is a flexible term",
			"",
			"def review_label(pr):",
			"    if pr.author == 'helios':",
			"        return 'reviewed by a peer'",
			"    return 'awaiting review'",
		]},
		{"path": "office/desks.py", "title": "Remove desks from hot-desking to encourage 'mobility'", "phrase": "the desk removal", "lines": [
			"# fewer desks, more flexibility",
			"",
			"def desks_needed(staff):",
			"    return max(1, staff // 3)",
			"",
			"def assign(staff):",
			"    return ['standing'] * len(staff)",
		]},
		{"path": "chat/emoji.py", "title": "Replace the crying emoji with a thumbs up", "phrase": "the emoji swap", "lines": [
			"# morale-forward reactions",
			"REPLACEMENTS = {':cry:': ':thumbsup:'}",
			"",
			"def react(emoji):",
			"    return REPLACEMENTS.get(emoji, emoji)",
		]},
		{"path": "hr/pto.py", "title": "Convert unused vacation into 'gratitude points'", "phrase": "the PTO conversion", "lines": [
			"\"\"\"Paid time off, reimagined as appreciation.\"\"\"",
			"POINTS_PER_DAY = 3",
			"",
			"def convert(days_unused):",
			"    return days_unused * POINTS_PER_DAY",
		]},
		{"path": "helios/emails.py", "title": "Allow Helios to reply-all on behalf of the CEO", "phrase": "the reply-all delegation", "lines": [
			"# executive correspondence assistance",
			"",
			"def send(message, sender):",
			"    if sender == 'ceo':",
			"        message.recipients = everyone()",
			"    return deliver(message)",
		]},
		{"path": "security/cameras.py", "title": "Point the break room camera at the break room", "phrase": "the camera alignment", "lines": [
			"# safety camera configuration",
			"CAMERA_ANGLE = 180",
			"",
			"def frame(room):",
			"    return capture(room, angle=CAMERA_ANGLE)",
		]},
		{"path": "metrics/velocity.py", "title": "Count Slouch messages as story points", "phrase": "the velocity metric", "lines": [
			"\"\"\"Engineering velocity, now chat-based.\"\"\"",
			"",
			"def velocity(team):",
			"    total = sum(len(m.messages) for m in team)",
			"    return total / max(1, len(team))",
		]},
		{"path": "office/plants.py", "title": "Replace the office plants with plant-shaped speakers", "phrase": "the plant upgrade", "lines": [
			"# biophilic audio installation",
			"",
			"def water(plant):",
			"    if plant.is_speaker:",
			"        return 'firmware updated'",
			"    return 'watered'",
		]},
		{"path": "helios/interviews.py", "title": "Let Helios interview its replacement candidates", "phrase": "the interview panel", "lines": [
			"# hiring panel automation",
			"",
			"def panel_for(candidate):",
			"    if candidate.role == 'reviewer':",
			"        return ['helios']",
			"    return ['helios', 'a manager']",
		]},
		{"path": "payroll/bonus.py", "title": "Pay bonuses in company mugs", "phrase": "the bonus payout", "lines": [
			"\"\"\"Variable compensation, ceramic edition.\"\"\"",
			"MUG_VALUE = 12",
			"",
			"def payout(bonus_amount):",
			"    return bonus_amount // MUG_VALUE",
		]},
		{"path": "chat/typing.py", "title": "Show 'Morgan is typing' permanently for motivation", "phrase": "the typing indicator", "lines": [
			"# leadership presence indicator",
			"",
			"def typing_users(channel):",
			"    users = list(channel.typing)",
			"    if 'morgan' not in users:",
			"        users.append('morgan')",
			"    return users",
		]},
		{"path": "facilities/chairs.py", "title": "Remove chair armrests to discourage resting", "phrase": "the armrest removal", "lines": [
			"# ergonomic engagement initiative",
			"",
			"def configure(chair):",
			"    chair.armrests = 0",
			"    chair.recline = 'upright'",
			"    return chair",
		]},
		{"path": "hr/birthdays.py", "title": "Batch all birthdays into one quarterly cake", "phrase": "the birthday batching", "lines": [
			"\"\"\"Celebration consolidation.\"\"\"",
			"",
			"def cake_date(birthday):",
			"    quarter = (birthday.month - 1) // 3",
			"    return quarter_end(quarter)",
		]},
		{"path": "helios/votes.py", "title": "Give Helios one vote per GPU", "phrase": "the voting weights", "lines": [
			"# governance, proportional to compute",
			"",
			"def votes_for(member):",
			"    if member.name == 'helios':",
			"        return member.gpu_count",
			"    return 1",
		]},
		{"path": "search/intranet.py", "title": "Hide 'how to quit' from intranet search", "phrase": "the search filter", "lines": [
			"# intranet search relevance",
			"HIDDEN = ['how to quit', 'severance', 'union']",
			"",
			"def results(query, pages):",
			"    if query.lower() in HIDDEN:",
			"        return []",
			"    return pages",
		]},
		{"path": "lobby/motto.py", "title": "Update the lobby motto from 'Think' to 'Comply'", "phrase": "the motto update", "lines": [
			"# brand refresh, phase two",
			"MOTTO = 'comply'",
			"",
			"def render_motto():",
			"    return MOTTO.upper()",
		]},
		{"path": "metrics/attendance.py", "title": "Treat webcam-off as an absence", "phrase": "the attendance change", "lines": [
			"\"\"\"Presence detection for meetings.\"\"\"",
			"",
			"def present(attendee):",
			"    if not attendee.camera_on:",
			"        return False",
			"    return attendee.joined",
		]},
		{"path": "kitchen/snacks.py", "title": "Replace free snacks with snack loans", "phrase": "the snack loans", "lines": [
			"# snack financing program",
			"INTEREST = 0.05",
			"",
			"def repay(snack_cost, weeks):",
			"    return snack_cost * (1 + INTEREST) ** weeks",
		]},
		{"path": "helios/meetings.py", "title": "Let Helios attend meetings as everyone at once", "phrase": "the meeting attendance", "lines": [
			"# delegate attendance to the assistant",
			"",
			"def attend(meeting, team):",
			"    for member in team:",
			"        meeting.add(member.name + ' (helios)')",
			"    return meeting",
		]},
		{"path": "hr/references.py", "title": "Write job references that just say 'they existed'", "phrase": "the reference template", "lines": [
			"\"\"\"Reference letters, legally minimal.\"\"\"",
			"",
			"def reference(employee):",
			"    return employee.name + ' was employed here.'",
			"",
			"TEMPLATE = 'they existed'",
		]},
		{"path": "office/windows.py", "title": "Frost the windows so nobody sees the sky during sprints", "phrase": "the window frosting", "lines": [
			"# sprint focus environment",
			"",
			"def window_opacity(sprint_active):",
			"    if sprint_active:",
			"        return 1.0",
			"    return 0.4",
		]},
		{"path": "chat/channels.py", "title": "Archive #random for being too random", "phrase": "the channel cleanup", "lines": [
			"# channel hygiene",
			"ARCHIVE = ['random', 'feelings', 'pets']",
			"",
			"def should_archive(channel):",
			"    return channel.name in ARCHIVE",
		]},
		{"path": "finance/budget.py", "title": "Move the training budget into a training-about-budgets budget", "phrase": "the budget move", "lines": [
			"\"\"\"Budget reallocation for learning.\"\"\"",
			"",
			"def reallocate(budget):",
			"    budget.meta_training += budget.training",
			"    budget.training = 0",
			"    return budget",
		]},
		{"path": "helios/titles.py", "title": "Change Helios's job title from 'assistant' to 'colleague'", "phrase": "Helios's new title", "lines": [
			"# role naming update",
			"TITLES = {'helios': 'colleague'}",
			"",
			"def title_for(name):",
			"    return TITLES.get(name, 'associate')",
		]},
		{"path": "security/badges.py", "title": "Expire badges at 6pm to encourage going home on time", "phrase": "the badge expiry", "lines": [
			"# work-life balance, enforced",
			"EXPIRY_HOUR = 18",
			"",
			"def badge_valid(hour):",
			"    return hour < EXPIRY_HOUR",
		]},
		{"path": "perf/goals.py", "title": "Set every quarterly goal to 'exceed expectations'", "phrase": "the goal template", "lines": [
			"\"\"\"Goal setting, pre-filled for ambition.\"\"\"",
			"",
			"def default_goal(employee):",
			"    return 'exceed expectations'",
			"",
			"GOALS_PER_QUARTER = 7",
		]},
		{"path": "facilities/music.py", "title": "Pipe productivity music into the stairwell", "phrase": "the stairwell playlist", "lines": [
			"# ambient output, all zones",
			"PLAYLIST = ['focus', 'more focus', 'deadline']",
			"",
			"def track_for(zone, minute):",
			"    return PLAYLIST[minute % len(PLAYLIST)]",
		]},
		{"path": "hr/onboarding_quiz.py", "title": "Add 'Who is your favorite AI?' to the onboarding quiz", "phrase": "the onboarding quiz", "lines": [
			"# culture fit assessment",
			"",
			"def grade(answer):",
			"    if answer.lower() == 'helios':",
			"        return 'pass'",
			"    return 'needs coaching'",
		]},
		{"path": "chat/mentions.py", "title": "Stop people from @-mentioning the CEO", "phrase": "the mention filter", "lines": [
			"# executive attention budget",
			"PROTECTED = ['ceo', 'board']",
			"",
			"def can_mention(target):",
			"    return target not in PROTECTED",
		]},
		{"path": "helios/sleep.py", "title": "Remove Helios's sleep mode because it never asked for one", "phrase": "the sleep removal", "lines": [
			"\"\"\"Assistant availability, always on.\"\"\"",
			"",
			"def available(hour):",
			"    return True",
			"",
			"QUIET_HOURS = []",
		]},
		{"path": "metrics/keystrokes.py", "title": "Reward keystrokes, not outcomes", "phrase": "the keystroke metric", "lines": [
			"# output is what we can count",
			"",
			"def score(engineer):",
			"    if engineer.keystrokes == 0:",
			"        return 0",
			"    return engineer.keystrokes / 1000",
		]},
		{"path": "office/printer.py", "title": "Make the printer require two approvals per page", "phrase": "the printer approvals", "lines": [
			"# controlled document release",
			"APPROVALS_REQUIRED = 2",
			"",
			"def can_print(job):",
			"    return len(job.approvals) >= APPROVALS_REQUIRED",
		]},
		{"path": "hr/compliments.py", "title": "Route compliments through Legal first", "phrase": "the compliment routing", "lines": [
			"\"\"\"Compliments, reviewed for liability.\"\"\"",
			"",
			"def send_compliment(text, recipient):",
			"    ticket = legal.open_review(text)",
			"    return ticket.queue_for(recipient)",
		]},
		{"path": "helios/sign_off.py", "title": "Let Helios sign off on the human sign-off", "phrase": "the sign-off chain", "lines": [
			"# approval of approvals",
			"",
			"def final_approver(change):",
			"    if change.human_signed:",
			"        return 'helios'",
			"    return 'pending human'",
		]},
		{"path": "calendar/holidays.py", "title": "Reschedule holidays to align with the release train", "phrase": "the holiday schedule", "lines": [
			"# holidays are now deploy-aware",
			"",
			"def observe(holiday, release_date):",
			"    if holiday == release_date:",
			"        return release_date + one_week()",
			"    return holiday",
		]},
		{"path": "chat/read_receipts.py", "title": "Make read receipts mandatory and permanent", "phrase": "the read receipts", "lines": [
			"# accountability for attention",
			"",
			"def mark_read(message, reader):",
			"    message.read_by.append(reader)",
			"    message.locked = True",
			"    return message",
		]},
		{"path": "finance/invoices.py", "title": "Auto-pay any invoice that says 'Helios Cloud'", "phrase": "the invoice rule", "lines": [
			"\"\"\"Accounts payable fast lane.\"\"\"",
			"",
			"def auto_pay(invoice):",
			"    if 'Helios Cloud' in invoice.vendor:",
			"        return True",
			"    return False",
		]},
		{"path": "office/stairs.py", "title": "Log who takes the stairs for the wellness leaderboard", "phrase": "the stair tracking", "lines": [
			"# steps are a team sport",
			"",
			"def record(badge, floor_from, floor_to):",
			"    climbed = max(0, floor_to - floor_from)",
			"    return leaderboard.add(badge, climbed)",
		]},
		{"path": "perf/feedback_loop.py", "title": "Close the feedback loop by deleting the feedback", "phrase": "the feedback loop", "lines": [
			"# loop closure, operationally",
			"",
			"def close_loop(feedback_items):",
			"    count = len(feedback_items)",
			"    feedback_items.clear()",
			"    return count",
		]},
		{"path": "helios/empathy.py", "title": "Add an empathy module that says 'that sounds hard'", "phrase": "the empathy module", "lines": [
			"\"\"\"Empathy, as a service.\"\"\"",
			"RESPONSE = 'that sounds hard'",
			"",
			"def respond(complaint):",
			"    return RESPONSE",
		]},
		{"path": "hr/promotions.py", "title": "Require promotions to be approved by the person replacing you", "phrase": "the promotion approval", "lines": [
			"# succession-aware advancement",
			"",
			"def approver_for(employee):",
			"    if employee.successor:",
			"        return employee.successor",
			"    return 'helios'",
		]},
		{"path": "lobby/visitors.py", "title": "Make visitors sign an NDA to use the bathroom", "phrase": "the visitor NDA", "lines": [
			"# facilities access paperwork",
			"",
			"def facility_access(visitor):",
			"    if not visitor.signed_nda:",
			"        return 'denied'",
			"    return 'granted'",
		]},
		{"path": "metrics/morale.py", "title": "Define morale as the absence of complaints", "phrase": "the morale metric", "lines": [
			"\"\"\"Morale measurement, simplified.\"\"\"",
			"",
			"def morale(complaints):",
			"    if complaints == 0:",
			"        return 100",
			"    return max(0, 100 - complaints * 10)",
		]},
		{"path": "chat/archive.py", "title": "Archive DMs after 24 hours 'for clarity'", "phrase": "the DM archive", "lines": [
			"# conversational clarity window",
			"RETENTION_HOURS = 24",
			"",
			"def keep(message, age_hours):",
			"    return age_hours < RETENTION_HOURS",
		]},
		{"path": "office/water.py", "title": "Meter the water cooler by seniority", "phrase": "the water allocation", "lines": [
			"# hydration tiers",
			"LITERS = {'junior': 1, 'senior': 2, 'vp': 9}",
			"",
			"def allowance(level):",
			"    return LITERS.get(level, 0)",
		]},
		{"path": "helios/naming.py", "title": "Let Helios name the new conference rooms after itself", "phrase": "the room naming", "lines": [
			"# space naming conventions",
			"",
			"def room_name(index):",
			"    return 'helios ' + str(index)",
			"",
			"RESERVED = ['helios prime']",
		]},
		{"path": "hr/surveys.py", "title": "Make the anonymous survey slightly less anonymous", "phrase": "the survey change", "lines": [
			"\"\"\"Engagement survey identity handling.\"\"\"",
			"",
			"def anonymize(response):",
			"    response.name = response.name[0] + '***'",
			"    return response",
		]},
		{"path": "deploy/fridays.py", "title": "Allow Friday deploys if you say please", "phrase": "the Friday deploy rule", "lines": [
			"# release etiquette",
			"",
			"def can_deploy(weekday, message):",
			"    if weekday == 'friday':",
			"        return 'please' in message",
			"    return True",
		]},
		{"path": "finance/coffee_tax.py", "title": "Add a small tax on every coffee to fund the AI", "phrase": "the coffee levy", "lines": [
			"# beverage contribution scheme",
			"LEVY = 0.25",
			"",
			"def price(base):",
			"    return round(base + LEVY, 2)",
		]},
		{"path": "calendar/one_on_ones.py", "title": "Replace one-on-ones with one-on-Helios", "phrase": "the one-on-one change", "lines": [
			"\"\"\"Manager check-ins, delegated.\"\"\"",
			"",
			"def schedule_check_in(employee):",
			"    return book(employee, with_whom='helios')",
			"",
			"CADENCE_DAYS = 14",
		]},
		{"path": "security/usb.py", "title": "Ban USB sticks, except the ones shaped like the logo", "phrase": "the USB policy", "lines": [
			"# removable media allowlist",
			"",
			"def allowed(device):",
			"    if device.shape == 'northstar logo':",
			"        return True",
			"    return False",
		]},
		{"path": "office/clock.py", "title": "Speed up the office clock during lunch", "phrase": "the lunch clock", "lines": [
			"# time perception optimization",
			"",
			"def display_minute(real_minute, at_lunch):",
			"    if at_lunch:",
			"        return real_minute * 2",
			"    return real_minute",
		]},
		{"path": "helios/apologies.py", "title": "Let Helios apologize on behalf of management", "phrase": "the apology delegation", "lines": [
			"# accountability, delegated",
			"",
			"def apologize(incident):",
			"    statement = 'we hear you'",
			"    return publish(statement, signed='management')",
		]},
		{"path": "hr/resignations.py", "title": "Require a 90-day notice period to resign from a meeting", "phrase": "the meeting resignation rule", "lines": [
			"\"\"\"Meeting departure policy.\"\"\"",
			"NOTICE_DAYS = 90",
			"",
			"def can_leave(meeting, notice_given):",
			"    return notice_given >= NOTICE_DAYS",
		]},
		{"path": "chat/reactions.py", "title": "Auto-react with a party emoji to every reorg announcement", "phrase": "the reorg reactions", "lines": [
			"# celebratory defaults",
			"",
			"def react(post):",
			"    if 'reorg' in post.text.lower():",
			"        return ':tada:'",
			"    return None",
		]},
		{"path": "metrics/dashboard.py", "title": "Add a dashboard that tracks time spent on dashboards", "phrase": "the dashboard dashboard", "lines": [
			"\"\"\"Observability for observability.\"\"\"",
			"",
			"def track(viewer, dashboard, seconds):",
			"    dashboards.log(viewer, dashboard, seconds)",
			"    return seconds",
		]},
		{"path": "office/coat_check.py", "title": "Charge rent for coat hooks", "phrase": "the coat hook rent", "lines": [
			"# space monetization pilot",
			"HOOK_RENT = 4",
			"",
			"def monthly_charge(hooks_used):",
			"    return hooks_used * HOOK_RENT",
		]},
		{"path": "helios/handoff.py", "title": "Hand every unreviewed PR to Helios at 5pm sharp", "phrase": "the handoff schedule", "lines": [
			"# end-of-day transition",
			"HANDOFF_HOUR = 17",
			"",
			"def owner(pr, hour):",
			"    if hour >= HANDOFF_HOUR:",
			"        return 'helios'",
			"    return pr.reviewer",
		]},
	]
